# h2-console
spring:
  h2:
    console:
      enabled: true

# DB URL
  datasource:
    url: jdbc:h2:mem:database;


# data.sql
  jpa:
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
